name: "Build all flutter archs"
on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  do_tests:
    name: Flutter Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            assets
            lib
            test
            scripts
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          
      - name: Download dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
  gen_icons:
    name: Generate icons & commit/push them
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check latest commit to assets
        id: assets
        # This job should not run when the latest commit to assets is older than 1 day
        # This is to reduce unnecessary running minutes
        run: |
          COMMITS=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits?path=assets&page=1&per_page=1")
          DAYS=$(echo $COMMITS | jq -r "((now - (.[0].commit.committer.date | fromdateiso8601) )  / (60*60*24)  | trunc)")
          echo "days=$DAYS" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        if: steps.assets.output.days == 0
        with:
          ref: main
      - uses: subosito/flutter-action@v2
        if: steps.assets.output.days == 0
        with:
          cache: true
      - name: Download dependencies
        run: flutter pub get
      - name: Generate flutter launcher icons
        if: steps.assets.output.days == 0
        run: flutter pub run flutter_launcher_icons
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.assets.output.days == 0
        with:
          commit_message: Generated icon files
          file_pattern: '*.xml *.json *.png'
  build_web:
    name: Build & publish for gh-pages
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [ do_tests, gen_icons ]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          
      - run: flutter pub get

      # Implement this troguh other action - run: dart run sqflite_common_ffi_web:setup
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /${{ github.event.repository.name }}/
  build_ios:
    name: Build iOS ipa
    needs: [ do_tests, gen_icons ]
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
        #with:
        #  sparse-checkout: |
        #    assets
        #    lib
        #    scripts
        #    ios
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          
      - name: Gathering dependencies
        run: flutter pub get
      - name: Build ios xcarchive
        run: flutter build ipa --release --no-codesign
      - name: Package xcarchive to ipa
        run: |
          brew install ldid
          chmod +x ${PWD}/scripts/package_ipa.sh 
          ${PWD}/scripts/package_ipa.sh ${PWD}/build/ios/archive/Runner.xcarchive .
      - name: Get current date
        id: date
        run: echo "date={$(date +'%Y-%m-%d')}" >> $GITHUB_ENV
      - name: Push artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: HW-manager-${{ env.date }}.ipa
          path: ./hw_manager_flutter.ipa

      - name: Upload files to a GitHub release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: hw-manager-${{ github.ref_name }}.ipa
          file: ./hw_manager_flutter.ipa
          tag: ${{ github.ref }}
  build_android:
    name: Build APK split by arch
    needs: [ do_tests, gen_icons ]
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: 'Set up JDK 17'
        uses: 'actions/setup-java@v1'
        with:
          java-version: '17'
          distribution: 'temurin'
        # Set up JDK 17 using the "actions/setup-java" action.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
        #with:
        #  sparse-checkout: |
        #    assets
        #    lib
        #    scripts
        #    ios
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'build-tools;30.0.3 platforms;android-32'
      - name: Gathering dependencies
        run: flutter pub get
      - name: Build apk
        id: 'apkbuild'
        run: 'flutter doctor -v; flutter build apk --split-per-abi && ls build/app/outputs/flutter-apk && echo "apkbuild=build/app/outputs/flutter-apk/" >> $GITHUB_ENV'
      - name: Get current date
        id: date
        run: echo "date={$(date +'%Y-%m-%d')}" >> $GITHUB_ENV
      - name: Push artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: HW-manager-${{ env.date }}
          path: build/app/outputs/flutter-apk/

      - name: Upload files to a GitHub release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: build/app/outputs/flutter-apk/*
          tag: ${{ github.ref }}
