name: "Build all flutter archs"
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  do_tests:
    name: Flutter Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositoriy
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          architecture: x64
          channel: 'stable'
      - name: Download dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
  build_ios:
    name: Build iOS ipa
    needs: do_tests
    runs-on: macos-latest
    steps:
      - name: Checkout repositoriy
        uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          architecture: x64
          channel: 'stable'
      - name: Build ios xcarchive
        run: |
          flutter pub get
          flutter build ipa --release --no-codesign
      - name: Package xcarchive to ipa
        run: |
          brew install ldid
          chmod +x ${PWD}/scripts/package_ipa.sh 
          ${PWD}/scripts/package_ipa.sh ${PWD}/build/ios/archive/Runner.xcarchive .
      - name: Get current date
        id: date
        run: echo "{date}={$(date +'%Y-%m-%d')}" >> $GITHUB_STATE
      - name: Push artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: HW-manager-${{ env.date }}.ipa
          path: ./hw_manager_flutter.ipa
      - run: mv ./hw_manager_flutter.ipa ./hw-manager-$GITHUB_REF_NAME.ipa
      - name: Release artifact
        uses: softprops/action-gh-release@v1
        with:
          files:
            ./hw-manager-${{ github.ref_name }}.ipa
