name: "[DEV] Build and Publish iOS"
on: [workflow_dispatch,push]
  
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repositoriy
        uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          architecture: x64
          channel: 'stable'
      - name: Build ios xcarchive
        run: flutter build ipa --release --no-codesign
      - name: Package xcarchive to ipa
        run: |
          brew install ldid
          chmod +x ${PWD}/scripts/package_ios.sh 
          ${PWD}/scripts/package_ipa.sh build/ipa/archive/Runner.xcarchive .
      - name: Get current date
        id: date
        run: echo "{date}={$(date +'%Y-%m-%d')}" >> $GITHUB_STATE
      - name: Push artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: HW-manager-${{ env.date }}.ipa
          path: ./hw_manager_flutter.ipa
