name: "[DEV] Build and Publish iOS"
on: workflow_dispatch
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      # Checks-out our repository under $GITHUB_WORKSPACE, so our job can access it
      - name: Checkout repositoriy
        uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          architecture: x64
          channel: 'stable'
      - name: Build ios app
        run: flutter build ios --release --no-codesign
      
