name: "[DEV] Build and Publish iOS"
on: workflow_dispatch
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repositoriy
        uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          architecture: x64
          channel: 'stable'
      - name: Build ios app
        run: flutter build ios --release --no-codesign
      - name: Push artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Runner.app
          path: /Users/runner/work/hw_manager_flutter/hw_manager_flutter/build/ios/iphoneos/Runner.app
